### PR TITLE
Index page is completed from what I can tell

### PR DESCRIPTION
**Pull request by vasubawa**
Title pretty much, let me know if something isn't working as intended., and also your monitor screen size since I use a 1440p so everything is a bit too spaced out for me.

### CODE REVIEW

**Review by John-Vazquez — CHANGES_REQUESTED** [review]
1. Hey I reviewed with Bill's owner, they like the logo how it was originally. please revert to that aswell as the nav bar.

2.  also, they do not want to have one font as Black and one as white. it has no color scheme. either we need to merge the color scheme somehow, or just pick one. for now, do not work on resizing anything we can fix that later, the most important is the styling for now.

3. They also like the words on the bottom left, not huge in the middle. The huge words with no design gives a non-professional look, I also personally agree. 

4. good work making the boxes the actual buttons, I ran that by them and thought it was nice.

**Review by vasubawa — COMMENTED** [review]
Hold up, color and text got messed up somehow. Aside from that, I reverted the asked changes except the nav one which I'm unsure on how they want it

**Review by vasubawa — COMMENTED** [review]
Alright, should be fixed

**Comment by vasubawa** [comment]
Nearly finished contact us page. Created a contact.css for the contact us page and moved it into a styles folder for organization. Added a map because the place was very empty feeling. Satellite views of one are possible, but it's probably going to cost money, I think. Design is a tad bit changes from Figma for consistency reasons so it matches the look from index page

**Review by John-Vazquez — APPROVED** [review]

**Pull request merged**
